### ISSUE TITLE
Goals for initial release

### ISSUE THREAD

**Issue by L-A** [L-A/Little-Jekyll#1]
## Todos
- [X] Basic application framework
- [X] Jekyll server thread manager & UI
- [X] Allow init of a new Jekyll site straight from Little Jekyll 🎉
- [X] Switch over to Electron's updated IPC scheme
- [x] Persist sites list & state
- [x] Persist server status on app quit & relaunch
- [x] ~~Interactive (?) installer for systems where Jekyll isn't available or found~~
- [x] Package Jekyll directly into the app
- [X] ~~Jekyll version picker / detection (at least for the latest stable, and the current Github supported version)~~
- [x] Sites action panel (delete, properties)

**Comment by L-A** [comment]
Moving future lists like this to a local tool.
